#!/usr/bin/env bash

check_factor()
{
    num=$1
    factors=($(factor "$num" | awk '{ for (i=2; i<=NF; i++) print $i }'))
    
    if [ "${#factors[@]}" -gt 0 ]; then
        echo -n "$num="
        for factor in "${factors[@]}"; do
            echo -n "$factor"
            if [ "$factor" != "${factors[-1]}" ]; then
                echo -n "*"
            fi
        done
        echo
    else
        echo "Error: Unable to factorize $num"
    fi
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read -r i; do
        check_factor "$i"
    done < "$1"
fi
