#!/usr/bin/python3
"""Factorize as many numbers as possible"""
import sys


def factor():
    """
    Search & convert files to a product value
    """
    try:
        revfile = sys.argv[1]
        with open(revfile) as f:
            for num in f:
                num = int(num)
                if num % 2 == 0:
                        print("{}={}*{}".format(num, num // 2, 2))
                        continue
                j = 3
                while j < num // 2:
                    if num % j == 0:
                        print("{}={}*{}".format(num, num // j, j))
                        break
                    j = j + 2
                if j == (num // 2) + 1:
                    print("{}={}*{}".format(num, num, 1))
    except (IndexError):
        pass


factor()
